# Generated by Django 5.1.3 on 2024-11-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
    ]
